### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by sabinebaer** [alexander-schranz/sulu-backend-bundle#29]
- I would add the dependency as require-dev instead of require  `composer require --dev l91/sulu-backend-bundle` instead of `composer require l91/sulu-backend-bundle`
- Bundle must be added to the AdminKernel
- Explain the `--extended` option more detailed.

**Comment by alexander-schranz** [comment]
`--dev` would only be when the `--extended` will be used else its a normal bundle.

**Comment by alexander-schranz** [comment]
other points are added to the readme file
